![data-x](https://raw.githubusercontent.com/afo/data-x-plaksha/master/imgsource/dx_logo.png)

---
# Pandas Introduction 
### with Stock Data and Correlation Examples


**Author list:** Ikhlaq Sidhu & Alexander Fred Ojala

**References / Sources:** 
Includes examples from Wes McKinney and the 10min intro to Pandas


**License Agreement:** Feel free to do whatever you want with this code

___

## What Does Pandas Do?
<img src="https://github.com/ikhlaqsidhu/data-x/raw/master/imgsource/pandas-p1.jpg">

## What is a Pandas Table Object?
<img src="https://github.com/ikhlaqsidhu/data-x/raw/master/imgsource/pandas-p2.jpg">


In [ ]:
# ## This table is a dictionary of sequences (like np arrays)
# <img src="https://github.com/ikhlaqsidhu/data-x/raw/master/imgsource/pandas-p3.jpg">


### Topics:
1. Dataframe creation
2. Reading data in dataFrames
3. Data Manipulation

## Import package

In [77]:
# pandas
import pandas as pd

In [78]:
# Extra packages
import numpy as np
import matplotlib.pyplot as plt # for plotting

# jupyter notebook magic to display plots in output
%matplotlib inline

plt.rcParams['figure.figsize'] = (10,6) # make the plots bigger

# Part:1 Creation Pandas dataframes

**Key Points:** Main data types in Pandas:
* Series (similar to numpy arrays, but with index)
* DataFrames (table or spreadsheet with Series in the columns)




### We use `pd.DataFrame( )` and can insert almost any data type as an argument

**Function:** `pd.DataFrame(data=None, index=None, columns=None, dtype=None, copy=False)`

Input data ca be a numpy ndarray (structured or homogeneous), dictionary, or DataFrame. 


### 1.1 Create Dataframe using an array

In [79]:
# Try it with an array

import numpy as np
np.random.seed(0) # set seed for reproducibility

a1 = np.random.randn(3)
a2 = np.random.randn(3)
a3 = np.random.randn(3)

print (a1)
print (a2)
print (a3)

[1.76405235 0.40015721 0.97873798]
[ 2.2408932   1.86755799 -0.97727788]
[ 0.95008842 -0.15135721 -0.10321885]


In [80]:
# Create our first DataFrame w/ an np.array - it becomes a column
df0 = pd.DataFrame(a1)
df0

0
0  1.764052
1  0.400157
2  0.978738

In [81]:
print(df0) # difference when you print and output of the last row

          0
0  1.764052
1  0.400157
2  0.978738


In [82]:
# Check type
type(df0)

pandas.core.frame.DataFrame

In [83]:
# DataFrame from list of np.arrays

df0 = pd.DataFrame([a1, a2, a3])
df0

# notice that there is no column label, only integer values,
# and the index is set automatically

0         1         2
0  1.764052  0.400157  0.978738
1  2.240893  1.867558 -0.977278
2  0.950088 -0.151357 -0.103219

In [84]:
# We can set column and index names

df0 = pd.DataFrame([a1, a2, a3],columns=['a1','a2','a3'],index=['a','b','c'])
df0

a1        a2        a3
a  1.764052  0.400157  0.978738
b  2.240893  1.867558 -0.977278
c  0.950088 -0.151357 -0.103219

In [85]:
# add  more columns to dataframe, like a dictionary, dimensions must match

df0['col4']=a2
df0

a1        a2        a3      col4
a  1.764052  0.400157  0.978738  2.240893
b  2.240893  1.867558 -0.977278  1.867558
c  0.950088 -0.151357 -0.103219 -0.977278

In [86]:
# DataFrame from 2D np.array

np.random.seed(0)
array_2d = np.array(np.random.randn(9)).reshape(3,3)
array_2d

array([[ 1.76405235,  0.40015721,  0.97873798],
       [ 2.2408932 ,  1.86755799, -0.97727788],
       [ 0.95008842, -0.15135721, -0.10321885]])

In [87]:
df0 = pd.DataFrame(array_2d,columns=['rand_normal_1','Random Again','Third'] \
                   , index=[100,200,99]) 

df0

rand_normal_1  Random Again     Third
100       1.764052      0.400157  0.978738
200       2.240893      1.867558 -0.977278
99        0.950088     -0.151357 -0.103219

### 1.2 Create Dataframe using an dictionary

In [88]:
# DataFrame from a Dictionary
dict1 = {'a1':a1, 'a2':a2,'a3':a3}
dict1

{'a1': array([1.76405235, 0.40015721, 0.97873798]),
 'a2': array([ 2.2408932 ,  1.86755799, -0.97727788]),
 'a3': array([ 0.95008842, -0.15135721, -0.10321885])}

In [89]:
df1 = pd.DataFrame(dict1,index=[1,2,3]) 
# note that we now have columns without assignment
df1

a1        a2        a3
1  1.764052  2.240893  0.950088
2  0.400157  1.867558 -0.151357
3  0.978738 -0.977278 -0.103219

In [90]:
# We can add a list with strings and ints as a column 
df1['L'] = ["List", 3, "words"]
df1

a1        a2        a3      L
1  1.764052  2.240893  0.950088   List
2  0.400157  1.867558 -0.151357      3
3  0.978738 -0.977278 -0.103219  words

### Pandas Series object
Every column is a Series. Like an np.array, but we can combine data types and it has its own index

In [96]:
type(df1['L'])

pandas.core.series.Series

In [97]:
df1['L'] # dtype object

1     List
2        3
3    words
Name: L, dtype: object

In [98]:
# different datatypes in a column
print(type(df1['L'][1]), type(df1['L'][2]))

<class 'str'> <class 'int'>


In [99]:
# Note: Every column in a DataFrame is a Series
print(df1['L'])
print()
print(type(df1['L']))

1     List
2        3
3    words
Name: L, dtype: object

<class 'pandas.core.series.Series'>


In [100]:
# Create a Series from a Python list
s = pd.Series([1,5,3]) # automatic index, 0,1,2...
s

0    1
1    5
2    3
dtype: int64

In [101]:
s2 = pd.Series([2, 3, 4], index = ['a','b','c']) #specific index
s2

a    2
b    3
c    4
dtype: int64

In [102]:
s2['a']

2

In [103]:
# We can add the Series s to the DataFrame above as column Series
# Remember to match indices
df1['Series'] = s
df1

a1        a2        a3      L  Series
1  1.764052  2.240893  0.950088   List     5.0
2  0.400157  1.867558 -0.151357      3     3.0
3  0.978738 -0.977278 -0.103219  words     NaN

In [104]:
# We can also rename columns
df1 = df1.rename(columns = {'L':'RenamedL'})
df1

a1        a2        a3 RenamedL  Series
1  1.764052  2.240893  0.950088     List     5.0
2  0.400157  1.867558 -0.151357        3     3.0
3  0.978738 -0.977278 -0.103219    words     NaN

In [105]:
# We can delete columns
del df1['RenamedL']
df1

a1        a2        a3  Series
1  1.764052  2.240893  0.950088     5.0
2  0.400157  1.867558 -0.151357     3.0
3  0.978738 -0.977278 -0.103219     NaN

In [ ]:
# or drop columns, see axis = 1
# does not change df1 if we don't set inplace=True
df1.drop('a2',axis=1) # returns a copy

In [ ]:
df1

In [ ]:
# or drop rows
df1.drop(1,axis=0)

# 1.3 Indexing / Slicing a Pandas Datframe

In [ ]:
# Example: view only one column
df1['a1']

In [ ]:
# Or view several column
df1[['a1','a3']]

In [ ]:
# slice of the DataFrame returned
# this slices the first three rows first followed by first 2 rows of the sliced frame
(df1[0:3][0:2])

In [ ]:
# Lets print the five first 2  elements of column a1
# This is a new Series (like a new table)
df1['a1'][0:2]

In [ ]:
# Lets print the 2 column, and top 2 values- note the list of columns
df1[['a1','a3']][0:2]

## Instead of double indexing, we can use loc, iloc

##### loc gets rows (or columns) with particular labels from the index.
#### iloc gets rows (or columns) at particular positions in the index (so it only takes integers).

## .iloc()

In [ ]:
df1.iloc[0,0]

In [ ]:


df1.iloc[0:2,0:2] # 2nd to 4th row, 4th to 5th column

In [ ]:
# iloc will also accept 2 'lists' of position numbers
df1.iloc[[0,2],[0,2]]

In [ ]:
1# Data only from row with index value '1'
print (df1.iloc[1])
print()
print (df1.iloc[1,:])

## .loc()

In [ ]:
# Usually we want to grab values by column names 

# Note: You have to know indices and columns
df1.loc[0:2,['a3','a2']]

In [ ]:
#  Boolean indexing
# return  full rows where a2>0

df1[df1['a2']>0]

# df1['a2']>0 - checks condition ans returns boolean and gives 



In [ ]:
# return column a3 values where a2 >0
df1['a3'][df1['a2']>0] 

In [ ]:
# If you want the values in an np array
npg = df1.loc[:,"a2"].values #otherwise it returns a  indexed series
print(type(npg))
print()
npg

### More Basic Statistics

In [ ]:
df1.describe()

In [ ]:
df1.describe().loc[['mean','std'],['a2','a3']]

In [ ]:
# We can change the index sorting
df1.sort_index(axis=0, ascending=False).head() # starts a year ago

#### For more functionalities check this notebook
https://github.com/ikhlaqsidhu/data-x/blob/master/02b-tools-pandas_intro-mplib_afo/legacy/10-minutes-to-pandas-w-data-x.ipynb



## Part 2: Reading data in pandas Dataframe


### Now, lets get some data in CSV format.

#### Description:
Aggregate data on applicants to graduate school at Berkeley for the six largest departments in 1973 classified by admission and sex.

https://vincentarelbundock.github.io/Rdatasets/doc/datasets/UCBAdmissions.html

In [106]:
df = pd.read_csv('data/ucbadmissions.csv')

In [107]:
# check statistics

Freq
count   24.000000
mean   188.583333
std    140.063624
min      8.000000
25%     80.000000
50%    170.000000
75%    302.500000
max    512.000000

In [ ]:
df.columns

In [ ]:
df.head()

In [ ]:
df.tail(2)

In [ ]:
df.groupby(['Admit','Gender']).sum()

In [ ]:
df.describe()

In [ ]:
df.info()

In [ ]:
pd.unique(df['Dept'])

In [ ]:
# Total number of applicants to Dept A
df[df['Dept']=='A']['Freq'].sum()

In [ ]:
df.groupby('Dept').sum()

In [ ]:
df.groupby('Dept').sum().plot.bar(grid=True)

# Install Pandas datareader to access APIs with Stock data

Read about data sources here (note, not all works anymore): https://pandas-datareader.readthedocs.io/en/latest/remote_data.html

In [ ]:
# Uncomment line below to install
# !pip install pandas_datareader

In [108]:
from pandas_datareader import data as web
from datetime import datetime as dt

### You can use the following code by creating your own API key (free, but limited), or using the chunk of code after it to create df_google and df_apple

In [ ]:
'''
#Delete the quotes if you'd like to use this code
pd.core.common.is_list_like = pd.api.types.is_list_like

df_google = web.DataReader('GOOGL', data_source='iex', start=dt(2018, 1, 1), end=dt.now(), api_key='pk_e393b229783840e2aac0516f90b8158b').reset_index()
df_apple = web.DataReader('AAPL', data_source='iex', start=dt(2018, 1, 1), end=dt.now(), api_key= 'pk_e393b229783840e2aac0516f90b8158b').reset_index()

# NOTE: change the api key! Create your own at: https://iexcloud.io/

'''

In [109]:

#Delete the quotes if you'd like to use this code

df_google = pd.read_csv('df_google.csv')
df_apple = pd.read_csv('df_apple.csv')



In [ ]:
df_google.head()
# Volume is the number of shares or contracts traded

In [ ]:
# check dtypes in each column
df_google.dtypes

###  Breakout: Check the file attributes & general statitics using Pandas 

In [110]:
# shape


(525, 7)

In [111]:
# show first five values


Unnamed: 0        date     open     high      low    close   volume
0           0  2018-01-02  1053.02  1075.98  1053.02  1073.21  1588268
1           1  2018-01-03  1073.93  1096.10  1073.43  1091.52  1565945
2           2  2018-01-04  1097.09  1104.08  1094.26  1095.76  1302569
3           3  2018-01-05  1103.45  1113.58  1101.80  1110.29  1512526
4           4  2018-01-08  1111.00  1119.16  1110.00  1114.21  1232221

In [112]:
# show last three


Unnamed: 0        date     open     high      low    close   volume
522         522  2020-01-30  1438.10  1455.25  1435.00  1454.25  1355472
523         523  2020-01-31  1467.86  1469.67  1427.06  1432.78  2191075
524         524  2020-02-03  1461.65  1486.30  1456.61  1482.60  3608760

In [113]:
# return column names


Index(['Unnamed: 0', 'date', 'open', 'high', 'low', 'close', 'volume'], dtype='object')

In [114]:
# get statistics- mean and std of "open" column


mean    1168.091200
std       98.155725
Name: open, dtype: float64

###  Convert the Date string  to pandas datetime object

In [115]:
df_google['date'][0]

'2018-01-02'

In [116]:
type(df_google['date'][0])

str

In [117]:
# convert string 'date' to datetime format
df_google['date'] = pd.to_datetime(df_google['date'],infer_datetime_format=True) 
df_google.head()

Unnamed: 0       date     open     high      low    close   volume
0           0 2018-01-02  1053.02  1075.98  1053.02  1073.21  1588268
1           1 2018-01-03  1073.93  1096.10  1073.43  1091.52  1565945
2           2 2018-01-04  1097.09  1104.08  1094.26  1095.76  1302569
3           3 2018-01-05  1103.45  1113.58  1101.80  1110.29  1512526
4           4 2018-01-08  1111.00  1119.16  1110.00  1114.21  1232221

In [ ]:
#  set index
df_google = df_google.set_index('date')

In [ ]:
# Then we can query date indices with strings
# Only January
df_google['2018-01']

In [ ]:
df_google['2018-01-03':'2018-01-09']

In [ ]:
df_google.loc['2018-02-28':'2018-04-21','open':'low'].head()

In [ ]:
#### Opening price statistics
open_price = df_google['open'].map(lambda x: int(np.floor(x/100)*100))
open_price.value_counts()

In [ ]:
open_price.hist()

In [ ]:
open_price.value_counts().sort_values().plot(kind='bar')

### Masks and Boolean Indexing

In [119]:
# Check mask 1
df_google['open']>240

0      True
1      True
2      True
3      True
4      True
       ... 
520    True
521    True
522    True
523    True
524    True
Name: open, Length: 525, dtype: bool

In [120]:
# Use mask 1
df_google['open'][df_google['open']>240]
# shows only rows with opening price greater than 1200

0      1053.02
1      1073.93
2      1097.09
3      1103.45
4      1111.00
        ...   
520    1441.74
521    1458.46
522    1438.10
523    1467.86
524    1461.65
Name: open, Length: 525, dtype: float64

In [121]:
# Show only the fisrt 10 rows where
df_google['open'][df_google['open']>240][:10]

0    1053.02
1    1073.93
2    1097.09
3    1103.45
4    1111.00
5    1118.44
6    1107.00
7    1112.31
8    1110.10
9    1140.31
Name: open, dtype: float64

In [122]:
# Show rows where opening stock is >240 before August 1st 2018
df_google[(df_google['open']>240) & (df_google.index < dt(2018,8,1))]

TypeError: '<' not supported between instances of 'int' and 'datetime.datetime'

In [ ]:
# we can also drop all NaN values
df_google[df_google>240]

In [ ]:
df_google[df_google>240].dropna(axis=0).head(10) #play with axis

In [ ]:
# another way to filter is with isin()

df_google[df_google['open'].isin([1170.62,1184.98])]

### Manipulating  Values


In [ ]:
# Recall
df_google.head(4)

In [ ]:
# All the ways to view (by location, by index, iat, etc) 
# can also be used to set values
# good for data normalization

df_google['volume'] = df_google['volume']/1000.0
df_google.head(4)

In [ ]:
# Change specific entry
df_google.iloc[0,1] = 2
df_google.head(3)

### More Statistics and Operations

In [ ]:
# mean by column, also try var() for variance
df_google.mean()   

In [ ]:
# Use the apply method to perform calculations on every elementi
df_google[0:10].apply(np.sqrt)

In [ ]:
df_google['month']=df_google.index.month_name()

In [ ]:
df_google.groupby('month')['open'].count()

In [ ]:
df_google[0:5].mean(axis = 1) # row means of first five rows

# PlotCorrelation
### Load several stocks

In [123]:
# Reload
dfg = pd.read_csv('data/googl.csv').drop('Unnamed: 0',axis=1) # Google stock data
dfa = pd.read_csv('data/apple.csv').drop('Unnamed: 0',axis=1) # Apple stock data
dfm = pd.read_csv('data/microsoft.csv').drop('Unnamed: 0',axis=1) # Google stock data
dfn = pd.read_csv('data/nike.csv').drop('Unnamed: 0',axis=1) # Apple stock data
dfb = pd.read_csv('data/boeing.csv').drop('Unnamed: 0',axis=1) # Apple stock data

In [124]:
dfb.head()

Date    Open    High     Low   Close    Volume
0  19-Jan-18  341.67  344.00  335.75  337.73   7264401
1  18-Jan-18  350.70  350.83  339.15  340.16   9458634
2  17-Jan-18  337.73  352.23  336.41  351.01   9699917
3  16-Jan-18  339.90  347.73  331.33  335.16  12305475
4  12-Jan-18  330.38  336.88  330.38  336.21   6559284

In [125]:
# Rename columns
dfg = dfg.rename(columns = {'Close':'GOOG'})
#print (dfg.head())

dfa = dfa.rename(columns = {'Close':'AAPL'})
#print (dfa.head())

dfm = dfm.rename(columns = {'Close':'MSFT'})
#print (dfm.head())

dfn = dfn.rename(columns = {'Close':'NKE'})
#print (dfn.head())

dfb = dfb.rename(columns = {'Close':'BA'})

In [126]:
dfb.head(2)

Date    Open    High     Low      BA   Volume
0  19-Jan-18  341.67  344.00  335.75  337.73  7264401
1  18-Jan-18  350.70  350.83  339.15  340.16  9458634

In [127]:
# Lets merge some tables
# They will all merge on the common column Date

df = dfg[['Date','GOOG']].merge(dfa[['Date','AAPL']])
df = df.merge(dfm[['Date','MSFT']])
df = df.merge(dfn[['Date','NKE']])
df = df.merge(dfb[['Date','BA']])

df.head()

Date     GOOG    AAPL   MSFT    NKE      BA
0  19-Jan-18  1143.50  178.46  90.00  67.21  337.73
1  18-Jan-18  1135.97  179.26  90.10  64.11  340.16
2  17-Jan-18  1139.10  179.10  90.14  63.81  351.01
3  16-Jan-18  1130.70  176.19  88.35  63.42  335.16
4  12-Jan-18  1130.65  177.09  89.60  64.67  336.21

In [128]:
df['Date'] = pd.to_datetime(df['Date'])
df = df.set_index('Date')
df.head()

GOOG    AAPL   MSFT    NKE      BA
Date                                             
2018-01-19  1143.50  178.46  90.00  67.21  337.73
2018-01-18  1135.97  179.26  90.10  64.11  340.16
2018-01-17  1139.10  179.10  90.14  63.81  351.01
2018-01-16  1130.70  176.19  88.35  63.42  335.16
2018-01-12  1130.65  177.09  89.60  64.67  336.21

In [ ]:
df.plot()

In [ ]:
df['2017'][['NKE','BA']].plot()

In [ ]:
# show a correlation matrix (pearson)
crl = df.corr()
crl

In [ ]:
crl.sort_values(by='GOOG',ascending=False)

In [ ]:
s = crl.unstack()
so = s.sort_values(ascending=False)
so[so<1]

In [ ]:
# zero mean to plot correlation
df.mean()

In [ ]:
sim=df-df.mean()
sim.tail()

In [ ]:
sim[['MSFT','BA']].plot()