![data-x](http://oi64.tinypic.com/o858n4.jpg)

---
# Cookbook 1: Intro to NumPy + Python 

**Author:** Kunal Desai, edited Ikhlaq Sidhu 1/22/2017

**License Agreement:** Feel free to do whatever you want with this code

___

*This notebook highlights basic types, commands, and operations in Python and Numpy *

### Strings
Python allows you to convert strings into different data types.

In [1]:
int('12')

12

In [2]:
float('1.2')

1.2

You can also turn any value into a string.

In [3]:
str(5)

'5'

You can also slice strings.

In [4]:
ex_string = "I love Data-X"
print ex_string[7:]
print ex_string[:6]
print ex_string[3:5]

Data-X
I love
ov


In [5]:
ex_string[:-1]

'I love Data-'

You can reverse strings.

In [6]:
# [start : stop : step]
ex_string[::-1]

'X-ataD evol I'

## Lists vs. Tuples

Lists are mutable objects while tuples are immutable.

In [7]:
#List
a = [1, 2, 3]
a[0] = 2
a

[2, 2, 3]

In [8]:
#Tuple
a = (0, 1, 2)
a[0] = 3
# immutable

TypeError: 'tuple' object does not support item assignment

# Introduction to NumPy

The core feauture that NumPy supports is its multi-dimensional arrays. In NumPy, dimensions are called axes and the number of axes is called a rank.

In [9]:
import numpy as np

Below is an array of rank 1 because it has one axis.

In [10]:
# We use a list as an argument input in making a NumPy Array

data = np.array([1, 2, 3])
print data


[1 2 3]


Below is an array of rank 2 because it has 2 axes. The first axis has dimension 2 and the second axis has dimension 3.

## Arrays are like lists, but different

In [11]:
# x and y are lists
x = list(range(5))
y = list(range(5,10))
print "x = ", x
print "y = ", y
print "x+y = ", x+y


x =  [0, 1, 2, 3, 4]
y =  [5, 6, 7, 8, 9]
x+y =  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [13]:
# now lets try with NumPy arrays:
xn = np.array(x)
yn = np.array(y)
print xn
print yn
print "xn + yn = ", xn + yn

[0 1 2 3 4]
[5 6 7 8 9]
xn + yn =  [ 5  7  9 11 13]


In [14]:
# if you need to join to numpy arrays, try hstack, vstack, column_stack, or concatenate
print np.hstack((xn,yn))
print np.concatenate((xn,yn))

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# An array is a sequence that can be manipulated easily
# All elements of an array should have the same type
# An arithmatic operation is applied to each element individually
# When two arrays are added, they must have the same size; corresponding elements 
# are added in the result


Creating arrays in NumPy, however, is different from creating the array.array library in Python. Here is how you do it:

In [15]:
# This list has two dimensions
[[1, 2, 3],
 [4, 5, 6]]

[[1, 2, 3], [4, 5, 6]]

In [16]:
data = np.array([[1, 2, 3], [4, 5, 6]])
print data

[[1 2 3]
 [4 5 6]]


In [17]:
# You can also transpose an array Matrix
print 'Python Transpose: \n', data.T, '\n'
print 'NumPy Transpose: \n', np.transpose(data)

Python Transpose: 
[[1 4]
 [2 5]
 [3 6]] 

NumPy Transpose: 
[[1 4]
 [2 5]
 [3 6]]


Remember that every time you declare an np.array, the argument must be in the form of a Python array. Ranges are a great tool to create these arrays.

In [18]:
#Creates array from 0 to before end: np.arange(end)
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
#Array increasing from start to end: np.arange(start, end)
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [20]:
#Array increasing from start to end by step: np.arange(start, end, step)
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

## Ranges:
#### A range is an array of consecutive numbers
np.arange(end): 
#### An array of increasing integers from 0 up to end
np.arange(start, end): 
#### An array of increasing integers from start up to end
np.arange(start, end, step): 
#### A range with step between consecutive values
The range always includes start but excludes end


Here is a quick example of a NumPy array and some helpful methods:

In [25]:
# Reshape is used to change the shape
a = np.arange(0, 15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [22]:
# If you want to know the shape, use 'shape'
a.shape

(3, 5)

In [23]:
# ndim tells us the number of dimensions of the array
a.ndim

2

In [26]:
#dtype.name tells us what type is each element in the array
a.dtype.name

'int64'

In [27]:
# And for total size:
a.size

15

In [29]:
# sum, min, max, .. are easy
print a
print a.sum()
print (0+14)*15/2

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
105
105


In [31]:
print a.sum(axis=0)
print a.sum(axis=1)

[15 18 21 24 27]
[10 35 60]


To get the cumulative product:

In [32]:
print np.arange(1, 10)
print np.cumprod(np.arange(1, 10))

[1 2 3 4 5 6 7 8 9]
[     1      2      6     24    120    720   5040  40320 362880]


To get the cumulative sum:

In [33]:
print np.arange(1, 10)
np.cumsum(np.arange(1, 10))

[1 2 3 4 5 6 7 8 9]


array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

You can also compare arrays

In [34]:
# Does this array have any elements that are "0"?
print np.arange(1, 10) == 0
np.any(np.arange(1, 10) == 0)

[False False False False False False False False False]


False

In [35]:
# Does this array have anny elements that are "1"?
print np.array([1, 1, 1, 1]) == 1
np.all(np.array([1, 1, 1, 1]) == 1)

[ True  True  True  True]


True

Creating a 3D array:

In [36]:
a = np.arange(0, 24).reshape(2, 3, 4)



Printing these arrays is fairly easy as well, just use the normal print command from Python

In [37]:
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


# Basic Operations

One of the coolest parts of NumPy is the ability for you to run operations on top of arrays. Here are some basic operations:

In [38]:
a = np.arange(11, 21)
b = np.arange(0, 10)
print "a = ",a
print "b = ",b
print a + b

a =  [11 12 13 14 15 16 17 18 19 20]
b =  [0 1 2 3 4 5 6 7 8 9]
[11 13 15 17 19 21 23 25 27 29]


In [39]:
a * b

array([  0,  12,  26,  42,  60,  80, 102, 126, 152, 180])

In [46]:
a ** 2

array([121, 144, 169, 196, 225, 256, 289, 324, 361, 400])

You can even do things like matrix operations

In [ ]:
a.dot(b)

In [47]:
# Matrix multiplication
c = np.arange(1,5).reshape(2,2)
print "c = "
print c
d = np.arange(5,9).reshape(2,2)
print "d = "
print d


c = 
[[1 2]
 [3 4]]
d = 
[[5 6]
 [7 8]]


In [48]:
print d.dot(c) 
print d

[[23 34]
 [31 46]]
[[5 6]
 [7 8]]
