![data-x](https://raw.githubusercontent.com/afo/data-x-plaksha/master/imgsource/dx_logo.png)

<br>


**References and Additional Resources**
<br>


> [TensorFlow Guides: Keras Sequential Model](https://www.tensorflow.org/guide/keras/sequential_model)<br>
> [Keras: The Sequential Model Guide](https://keras.io/guides/sequential_model/)<br>
> [TensorBoard in Notebooks](https://www.tensorflow.org/tensorboard/tensorboard_in_notebooks)

___

#### NAME:

#### STUDENT ID:
___

## [Solutions] Homework - TensorFlow

In [1]:
# load the dependencies
import numpy as np
import tensorflow as tf

# check whether tf version is 2.x
tf.__version__

'2.2.0'

<br>

## Understanding Tensors

___

<br>

**Create the following tensors:**
> `a` is a constant tensor with value 1. (float)<br>
> `b` is a constant tensor with value 2. (float)<br>
> `c` is an np.array with one consant value 3. (float)

In [2]:
# tensors
a = tf.constant(1.)
b = tf.constant(2.)
c = tf.constant(np.array(3.))

In [ ]:
# identify and fix the problem with following addition opperation for the defined constants
a + b + c

<br>

**Problem:**

> `a` and `b` are float tensors, while `c` is a double tensor. As such the different data types prevent the operation. 

<br>

**Use TensorFlow functions to solve** `a+b+c`

In [4]:
# your code here
# add same dimension first
op1 = tf.add(a, b)
op1

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [5]:
# convert double to float
c = tf.dtypes.cast(c, tf.float32)

# perform operation
op2 =tf.add(op1, c)
op2

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

<br>

**Visualize the operation,** `a+b+c` **(Writing a graph to TensorBoard using TensorFlow 2.0)**

> **Tip:** You will need to use the [\@tf.function](https://www.tensorflow.org/api_docs/python/tf/function) in order ot compile a [TensorFlow graph](https://www.tensorflow.org/api_docs/python/tf/Graph).  You will also need to set up logging using [tf.summary.create_file_writer](https://www.tensorflow.org/api_docs/python/tf/summary/create_file_writer)

In [6]:
# @tf.function
@tf.function
def f(x, y, z):
    return(x + y + z)

In [7]:
# Set up logging.
logdir = './logs/func'
writer = tf.summary.create_file_writer(logdir)

In [8]:
# declare data for function
a = tf.constant(1.)
b = tf.constant(2.)
c = tf.constant(np.array(3.))
c = tf.dtypes.cast(c, tf.float32)

In [9]:
# set tracing
tf.summary.trace_on(graph=True, profiler=True)

# Call tf.function when tracing.
val = f(a, b, c)

# write summary logs
with writer.as_default():
  tf.summary.trace_export(
      name="a + b + c",
      step=0,
      profiler_outdir=logdir)

In [10]:
# notebook extension
%load_ext tensorboard

In [12]:
# launch tensorboard
%tensorboard --logdir ./logs/func

Reusing TensorBoard on port 6007 (pid 879), started 0:00:06 ago. (Use '!kill 879' to kill it.)

<br>

## Computing Gradients the TensorFlow way

___

<br>

**The following is a non-optimized, simple, way to calculate gradients for a given function.**

In [13]:
# function definition =>
@tf.function
def g(x, y):
    return(5 * x ** 2 + 3 * x * y)

___

**Note:** for `[x, y] = [tf.Variable(1.), tf.Variable(1.)]` the result is

```python 
    [<tf.Tensor: shape=(), dtype=float32, numpy=13.0>,
     <tf.Tensor: shape=(), dtype=float32, numpy=3.0>]
```

___

<br>

**To Do:**<br>
> Complete the following code to compute the gradients using [`tf.GradientTape()`](https://www.tensorflow.org/api_docs/python/tf/GradientTape) -- TensorFlow V2 Automatic Differentiation

In [14]:
x = tf.Variable(1.)
y = tf.Variable(1.)

with tf.GradientTape() as tape:
    z = g(x, y)

In [15]:
# calculate gradients
grads = tape.gradient(z, [x, y]) 


print('Gradients:')
grads

Gradients:


[<tf.Tensor: shape=(), dtype=float32, numpy=13.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=3.0>]

___

### Deliverables

Please submit your the following via the instructed method (lecture or Syllabus): 

>(1) A copy of your work, either a downloaded notebook or a pdf, by the assignment deadline

<br>

**Note:** Don't gorget to restart your kernel prior to extracting your data.

>```Kernel --> Restart Kernel and Run all Cells```<br>
>```File --> Export Notebooks As --> PDF``` (or as instructed)

___