<div align="center">
    <img src= "DataX_blue_wide_logo.png" align="center" width="100%">
</div>

### **HOMEWORK**- TENSORS, AND GRADIENTS

<br>

<div align="center" style="font-size:12px; font-family:FreeMono; font-weight: 100; font-stretch:ultra-condensed; line-height: 1.0; color:#2A2C2B">
    <img src="tensorflow_thumbnail-01.png" align="center" width="40%" padding="0px"><br>
    <br>
</div>

<br>

<br>

**m410_shallow_neural_networks_introduction_to_tensorflow_v2**  coverd tensor creation, access, and manipulation.  We also covered the concept of functions over sessions. This notebook, test your knowledge of the **\@tf.function**, and visualizing graphs in TensorBoard.  For additional materials related to TensorFlow, Keras, and deep learning in general, make sure to visit the [**Data-X**](https://datax.berkeley.edu/) website.

<br>

**Author list:** [Rajarathnam Balakrishnan](https://www.linkedin.com/in/rajarathnam-balakrishnan-7b447b135/) and [Elias Casto Hernandez](https://www.linkedin.com/in/ehcastroh/)

**References and Additional Resources**
<br>


> [TensorFlow Guides: Keras Sequential Model](https://www.tensorflow.org/guide/keras/sequential_model)<br>
> [Keras: The Sequential Model Guide](https://keras.io/guides/sequential_model/)<br>
> [TensorBoard in Notebooks](https://www.tensorflow.org/tensorboard/tensorboard_in_notebooks)

___

#### NAME:

#### STUDENT ID:

<hr style="border: 2px solid#003262;" />

#### PART 1: UNDERSTANDING TENSORS

<div align="center" style="font-size:12px; font-family:FreeMono; font-weight: 100; font-stretch:ultra-condensed; line-height: 1.0; color:#2A2C2B">
    <img src="tf_logo_social.png" align="center" width="30%" padding="0"><br>
    <br>
</div>

<br>



<br>

In [1]:
# load the dependencies
import numpy as np
import tensorflow as tf

# check whether tf version is 2.x
tf.__version__

'2.2.0'

<br>

**1.1 Create the following tensors:**
> `a` is a constant tensor with value 1. (float)<br>
> `b` is a constant tensor with value 2. (float)<br>
> `c` is an np.array with one consant value 3. (float)

In [2]:
# tensors
a = tf.constant(1.)
b = tf.constant(2.)
c = tf.constant(np.array(3.))

In [ ]:
# identify and fix the problem with following addition opperation for the defined constants
a + b + c

**Problem:**

> your answer here (or add a cell and comment your Python)

<br>

**1.2 Use TensorFlow functions to solve** `a+b+c`

In [7]:
# your code here


<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

<br>

**1.3 Visualize the operation,** `a+b+c` **(Writing a graph to TensorBoard using TensorFlow 2.0)**

> **Tip:** You will need to use the [\@tf.function](https://www.tensorflow.org/api_docs/python/tf/function) in order ot compile a [TensorFlow graph](https://www.tensorflow.org/api_docs/python/tf/Graph).  You will also need to set up logging using [tf.summary.create_file_writer](https://www.tensorflow.org/api_docs/python/tf/summary/create_file_writer)

In [55]:
# @tf.function
@tf.function
def f(x, y, z):
    return(x + y + z)

In [ ]:
# your work here

<hr style="border: 1px solid#003262;" />

#### PART 2: COMPUTING GRADIENTS THE TENSORFLOW WAY!

In [4]:
import numpy as np
import tensorflow as tf

<br>

**2.1 The following is a non-optimized, simple, way to calculate gradients for a given function.**

In [5]:
# function definition =>
@tf.function
def g(x, y):
    return(5 * x ** 2 + 3 * x * y)

___

**Note:** for `[x, y] = [tf.Variable(1.), tf.Variable(1.)]` the result is

```python 
    [<tf.Tensor: shape=(), dtype=float32, numpy=13.0>,
     <tf.Tensor: shape=(), dtype=float32, numpy=3.0>]
```

___

<br>

**To Do:**<br>
> Complete the following code to compute the gradients using [`tf.GradientTape()`](https://www.tensorflow.org/api_docs/python/tf/GradientTape) -- TensorFlow V2 Automatic Differentiation

In [ ]:
x= tf.Variable(1.)
y = tf.Variable(1.)

with tf.GradientTape() as tape:
    
    z =     # fill the missing code

# calculate gradients
grads = tape.gradient(   ) # fill the arguments

print('Gradients:')
grads

<hr style="border: 2px solid#003262;" />

### **DELIVERABLES**

Please submit your the following via the instructed method (lecture or Syllabus):

>(1) A copy of your work, either a downloaded notebook or a pdf, by the assignment deadline

<br>

**Note:** Don't gorget to restart your kernel prior to extracting your data.

>```Kernel --> Restart Kernel and Run all Cells```<br>
>```File --> Export Notebooks As --> PDF``` (or as instructed)


<hr style="border: 2px solid#003262;" />